import { ImageAsset } from './types';

export const categories = [
  'Todos',
  'Logos',
  'Acemax',
  'Infraestructura',
  'Personal'
];

export const mockAssets: ImageAsset[] = [
  {
    id: '1',
    url: import.meta.env.BASE_URL + 'imagenes/acemax.png',
    title: 'Workspace Logo Ideas',
    author: 'Acemax Datacenter',
    tags: ['Logos', 'Acemax'],
    downloads: 1204,
    likes: 342,
    aspectRatio: 'video',
  },
  {
    id: '2',
    url: import.meta.env.BASE_URL + 'imagenes/acemaxFB.jpg',
    title: 'Infraestructura Code',
    author: 'Acemax TI',
    tags: ['Infraestructura'],
    downloads: 890,
    likes: 215,
    aspectRatio: 'square',
  },
  {
    id: '3',
    url: import.meta.env.BASE_URL + 'imagenes/acemaxFB.png',
    title: 'Personal Branding',
    author: 'Acemax Mesa de ayuda',
    tags: ['Personal', 'Logos'],
    downloads: 3400,
    likes: 1200,
    aspectRatio: 'portrait',
  },
  {
    id: '4',
    url: import.meta.env.BASE_URL + 'imagenes/acemaxsistemas-removebg-preview.png',
    title: 'Acemax Workspace',
    author: 'Acemax',
    tags: ['Acemax'],
    downloads: 654,
    likes: 130,
    aspectRatio: 'video',
  },
  {
    id: '5',
    url: import.meta.env.BASE_URL + 'imagenes/acemaxsistemas.png',
    title: 'Logos App Design',
    author: 'Acemax TI',
    tags: ['Logos'],
    downloads: 2100,
    likes: 850,
    aspectRatio: 'square',
  },
  {
    id: '6',
    url: import.meta.env.BASE_URL + 'imagenes/empresa4.webp',
    title: 'Abstract 3D Logo',
    author: 'Logo',
    tags: ['Logos'],
    downloads: 4500,
    likes: 3100,
    aspectRatio: 'video',
  },
  {
    id: '7',
    url: import.meta.env.BASE_URL + 'imagenes/Gemini_Generated_Image_8ecbj8ecbj8ecbj8.png',
    title: 'Personal Tech',
    author: 'Acemax',
    tags: ['Personal', 'Acemax'],
    downloads: 432,
    likes: 95,
    aspectRatio: 'portrait',
  },
  {
    id: '8',
    url: import.meta.env.BASE_URL + 'imagenes/isotipo.webp',
    title: 'Server Infraestructura',
    author: 'Logo',
    tags: ['Infraestructura'],
    downloads: 1800,
    likes: 670,
    aspectRatio: 'video',
  },
  {
    id: '9',
    url: import.meta.env.BASE_URL + 'imagenes/logo.webp',
    title: 'Acemax Desk',
    author: 'Logo',
    tags: ['Acemax', 'Personal'],
    downloads: 920,
    likes: 410,
    aspectRatio: 'square',
  },
  {
    id: '10',
    url: import.meta.env.BASE_URL + 'imagenes/logoB.webp',
    title: 'Social Media Logos',
    author: 'Logo',
    tags: ['Logos'],
    downloads: 3210,
    likes: 1540,
    aspectRatio: 'portrait',
  }
];